import { Slate } from 'slates';
import { spec } from './spec';
import {
  searchDashboards,
  getDashboard,
  saveDashboard,
  deleteDashboard,
  listFolders,
  createFolder,
  updateFolder,
  deleteFolder,
  listDataSources,
  getDataSource,
  createDataSource,
  updateDataSource,
  deleteDataSource,
  listAlertRules,
  getAlertRule,
  createAlertRule,
  updateAlertRule,
  deleteAlertRule,
  listContactPoints,
  createContactPoint,
  deleteContactPoint,
  getNotificationPolicies,
  updateNotificationPolicies,
  findAnnotations,
  createAnnotation,
  updateAnnotation,
  deleteAnnotation,
  listSnapshots,
  createSnapshot,
  deleteSnapshot,
  searchTeams,
  createTeam,
  getTeamMembers,
  addTeamMember,
  removeTeamMember,
  deleteTeam,
  listOrgUsers,
  addOrgUser,
  updateOrgUserRole,
  removeOrgUser
} from './tools';
import { alertNotification, annotationEvents } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    searchDashboards,
    getDashboard,
    saveDashboard,
    deleteDashboard,
    listFolders,
    createFolder,
    updateFolder,
    deleteFolder,
    listDataSources,
    getDataSource,
    createDataSource,
    updateDataSource,
    deleteDataSource,
    listAlertRules,
    getAlertRule,
    createAlertRule,
    updateAlertRule,
    deleteAlertRule,
    listContactPoints,
    createContactPoint,
    deleteContactPoint,
    getNotificationPolicies,
    updateNotificationPolicies,
    findAnnotations,
    createAnnotation,
    updateAnnotation,
    deleteAnnotation,
    listSnapshots,
    createSnapshot,
    deleteSnapshot,
    searchTeams,
    createTeam,
    getTeamMembers,
    addTeamMember,
    removeTeamMember,
    deleteTeam,
    listOrgUsers,
    addOrgUser,
    updateOrgUserRole,
    removeOrgUser
  ],
  triggers: [alertNotification, annotationEvents]
});
