import { Slate } from 'slates';
import { spec } from './spec';
import {
  createContact,
  getContact,
  updateContact,
  findContacts,
  createAccount,
  getAccount,
  updateAccount,
  findAccounts,
  createLead,
  getLead,
  updateLead,
  findLeads,
  createActivity,
  findActivities,
  createTask,
  addNote,
  searchCrm,
  listProducts,
  listPipelinesStages,
  listUsersTeams,
  listActivityTypes,
  listSources,
  getTimeline,
} from './tools';
import {
  entityChanges,
  newLeads,
  newContacts,
  newAccounts,
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    createContact,
    getContact,
    updateContact,
    findContacts,
    createAccount,
    getAccount,
    updateAccount,
    findAccounts,
    createLead,
    getLead,
    updateLead,
    findLeads,
    createActivity,
    findActivities,
    createTask,
    addNote,
    searchCrm,
    listProducts,
    listPipelinesStages,
    listUsersTeams,
    listActivityTypes,
    listSources,
    getTimeline,
  ],
  triggers: [
    entityChanges,
    newLeads,
    newContacts,
    newAccounts,
  ],
});
