import { Slate } from 'slates';
import { spec } from './spec';
import {
  createOptimization,
  getOptimization,
  getRoutes,
  updateRoute,
  deleteRoute,
  duplicateRoute,
  createOrder,
  getOrders,
  updateOrder,
  deleteOrders,
  createContact,
  getContacts,
  updateContact,
  deleteContacts,
  geocode,
  getVehicles,
  createVehicle,
  updateVehicle,
  deleteVehicle,
  getTeamMembers,
  createTeamMember,
  updateTeamMember,
  deleteTeamMember,
  addNote,
  getNotes,
  getActivities,
  getAvoidanceZones,
  createAvoidanceZone,
  deleteAvoidanceZone,
  getTerritories,
  createTerritory,
  deleteTerritory,
  getTrackingHistory,
  setGpsPosition
} from './tools';
import { activityWebhook, activityPolling } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    createOptimization,
    getOptimization,
    getRoutes,
    updateRoute,
    deleteRoute,
    duplicateRoute,
    createOrder,
    getOrders,
    updateOrder,
    deleteOrders,
    createContact,
    getContacts,
    updateContact,
    deleteContacts,
    geocode,
    getVehicles,
    createVehicle,
    updateVehicle,
    deleteVehicle,
    getTeamMembers,
    createTeamMember,
    updateTeamMember,
    deleteTeamMember,
    addNote,
    getNotes,
    getActivities,
    getAvoidanceZones,
    createAvoidanceZone,
    deleteAvoidanceZone,
    getTerritories,
    createTerritory,
    deleteTerritory,
    getTrackingHistory,
    setGpsPosition
  ],
  triggers: [activityWebhook, activityPolling]
});
