import { Slate } from 'slates';
import { spec } from './spec';
import {
  sendEmail,
  sendBatchEmails,
  getEmail,
  cancelScheduledEmail,
  createDomain,
  getDomain,
  updateDomain,
  listDomains,
  verifyDomain,
  deleteDomain,
  createContact,
  getContact,
  updateContact,
  listContacts,
  deleteContact,
  createBroadcast,
  getBroadcast,
  sendBroadcast,
  listBroadcasts,
  deleteBroadcast,
  createTemplate,
  getTemplate,
  updateTemplate,
  listTemplates,
  publishTemplate,
  deleteTemplate,
  createAudience,
  listAudiences,
  deleteAudience,
  createApiKey,
  listApiKeys,
  deleteApiKey,
  listReceivedEmails,
  getReceivedEmail
} from './tools';
import { emailEvents, contactEvents, domainEvents } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    sendEmail,
    sendBatchEmails,
    getEmail,
    cancelScheduledEmail,
    createDomain,
    getDomain,
    updateDomain,
    listDomains,
    verifyDomain,
    deleteDomain,
    createContact,
    getContact,
    updateContact,
    listContacts,
    deleteContact,
    createBroadcast,
    getBroadcast,
    sendBroadcast,
    listBroadcasts,
    deleteBroadcast,
    createTemplate,
    getTemplate,
    updateTemplate,
    listTemplates,
    publishTemplate,
    deleteTemplate,
    createAudience,
    listAudiences,
    deleteAudience,
    createApiKey,
    listApiKeys,
    deleteApiKey,
    listReceivedEmails,
    getReceivedEmail
  ],
  triggers: [emailEvents, contactEvents, domainEvents]
});
