import { Slate } from 'slates';
import { spec } from './spec';
import {
  createContact,
  updateContact,
  getContact,
  listContacts,
  deleteContact,
  createDeal,
  updateDeal,
  listDeals,
  deleteDeal,
  createAction,
  updateAction,
  listActions,
  deleteAction,
  createNote,
  updateNote,
  listNotes,
  logCall,
  logMeeting,
  listCompanies,
  updateCompany,
  getActionStream,
  listStatusesAndSources,
} from './tools';
import {
  contactEvents,
  actionEvents,
  dealEvents,
  noteEvents,
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    createContact,
    updateContact,
    getContact,
    listContacts,
    deleteContact,
    createDeal,
    updateDeal,
    listDeals,
    deleteDeal,
    createAction,
    updateAction,
    listActions,
    deleteAction,
    createNote,
    updateNote,
    listNotes,
    logCall,
    logMeeting,
    listCompanies,
    updateCompany,
    getActionStream,
    listStatusesAndSources,
  ],
  triggers: [
    contactEvents,
    actionEvents,
    dealEvents,
    noteEvents,
  ],
});
