import { Slate } from 'slates';
import { spec } from './spec';
import {
  listProjectsTool,
  getIssueTool,
  createIssueTool,
  updateIssueTool,
  deleteIssueTool,
  queryIssuesTool,
  listIssueTypesTool,
  addSubtaskTool,
  updateSubtaskTool,
  deleteSubtaskTool,
  addIssueRelationTool,
  removeIssueRelationTool,
  listSprintsTool,
  createSprintTool,
  updateSprintTool,
  deleteSprintTool,
  listEpicsTool,
  createEpicTool,
  updateEpicTool,
  deleteEpicTool,
  listVersionsTool,
  createVersionTool,
  updateVersionTool,
  deleteVersionTool,
  manageVersionLifecycleTool,
  listCommentsTool,
  addCommentTool,
  updateCommentTool,
  deleteCommentTool,
  listTagsTool,
  createTagTool,
  deleteTagTool,
  listOrgMembersTool,
  listProjectMembersTool
} from './tools';
import {
  issueEventsTrigger,
  commentEventsTrigger,
  sprintEventsTrigger,
  subtaskEventsTrigger,
  attachmentEventsTrigger
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    listProjectsTool,
    getIssueTool,
    createIssueTool,
    updateIssueTool,
    deleteIssueTool,
    queryIssuesTool,
    listIssueTypesTool,
    addSubtaskTool,
    updateSubtaskTool,
    deleteSubtaskTool,
    addIssueRelationTool,
    removeIssueRelationTool,
    listSprintsTool,
    createSprintTool,
    updateSprintTool,
    deleteSprintTool,
    listEpicsTool,
    createEpicTool,
    updateEpicTool,
    deleteEpicTool,
    listVersionsTool,
    createVersionTool,
    updateVersionTool,
    deleteVersionTool,
    manageVersionLifecycleTool,
    listCommentsTool,
    addCommentTool,
    updateCommentTool,
    deleteCommentTool,
    listTagsTool,
    createTagTool,
    deleteTagTool,
    listOrgMembersTool,
    listProjectMembersTool
  ],
  triggers: [
    issueEventsTrigger,
    commentEventsTrigger,
    sprintEventsTrigger,
    subtaskEventsTrigger,
    attachmentEventsTrigger
  ]
});
