import { Slate } from 'slates';
import { spec } from './spec';
import {
  createTicket,
  getTicket,
  updateTicket,
  listTickets,
  deleteTicket,
  search,
  listUsers,
  getUser,
  createUser,
  updateUser,
  deleteUser,
  listOrganizations,
  getOrganization,
  createOrganization,
  updateOrganization,
  deleteOrganization,
  listArticles,
  getArticle,
  createArticle,
  updateArticle,
  deleteArticle,
  listViews,
  listGroups,
  listHelpCenterCategories,
  listTicketComments,
  listTicketFields,
  listMacros
} from './tools';
import { ticketEvents, userEvents, organizationEvents, articleEvents } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    createTicket,
    getTicket,
    updateTicket,
    listTickets,
    deleteTicket,
    search,
    listUsers,
    getUser,
    createUser,
    updateUser,
    deleteUser,
    listOrganizations,
    getOrganization,
    createOrganization,
    updateOrganization,
    deleteOrganization,
    listArticles,
    getArticle,
    createArticle,
    updateArticle,
    deleteArticle,
    listViews,
    listGroups,
    listHelpCenterCategories,
    listTicketComments,
    listTicketFields,
    listMacros
  ],
  triggers: [ticketEvents, userEvents, organizationEvents, articleEvents]
});
