import { SlateTool } from 'slates';
import { FirefliesClient } from '../lib/client';
import { spec } from '../spec';
import { z } from 'zod';

export let getAiApps = SlateTool.create(
  spec,
  {
    name: 'Get AI App Results',
    key: 'get_ai_apps',
    description: `Retrieve results generated by AI Apps installed in your Fireflies workspace. Filter by a specific AI app or transcript to see the prompts and responses generated.`,
    tags: {
      readOnly: true,
    },
  }
)
  .input(z.object({
    appId: z.string().optional().describe('Filter results by a specific AI App ID'),
    transcriptId: z.string().optional().describe('Filter results by a specific transcript ID'),
    limit: z.number().optional().describe('Maximum number of results to return (max 10, default 10)'),
    skip: z.number().optional().describe('Number of results to skip for pagination'),
  }))
  .output(z.object({
    outputs: z.array(z.object({
      transcriptId: z.string().nullable().describe('Associated transcript ID'),
      userId: z.string().nullable().describe('User who triggered the app'),
      appId: z.string().nullable().describe('AI App identifier'),
      createdAt: z.string().nullable().describe('When the result was generated'),
      title: z.string().nullable().describe('Result title'),
      prompt: z.string().nullable().describe('The prompt used by the AI App'),
      response: z.string().nullable().describe('The AI-generated response'),
    })).describe('AI App output results'),
  }))
  .handleInvocation(async (ctx) => {
    let client = new FirefliesClient({ token: ctx.auth.token });

    let result = await client.getAiApps({
      appId: ctx.input.appId,
      transcriptId: ctx.input.transcriptId,
      limit: ctx.input.limit,
      skip: ctx.input.skip,
    });

    let outputs = (result?.outputs || []).map((o: any) => ({
      transcriptId: o.transcript_id ?? null,
      userId: o.user_id ?? null,
      appId: o.app_id ?? null,
      createdAt: o.created_at ?? null,
      title: o.title ?? null,
      prompt: o.prompt ?? null,
      response: o.response ?? null,
    }));

    return {
      output: { outputs },
      message: `Retrieved **${outputs.length}** AI App result(s).`,
    };
  })
  .build();
