import { Slate } from 'slates';
import { spec } from './spec';
import {
  listSources,
  getSource,
  createSource,
  updateSource,
  deleteSource,
  listSourceTypes,
  getDestination,
  createDestination,
  updateDestination,
  deleteDestination,
  listStreams,
  getStream,
  updateStreamSelection,
  startReplication,
  stopReplication,
  listExtractions,
  listLoads,
  getExtractionLogs,
  listNotifications,
  manageCustomEmail,
  managePostLoadHook,
  pushData,
  validateData,
} from './tools';
import {
  postLoadTrigger,
  extractionStatusTrigger,
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    listSources,
    getSource,
    createSource,
    updateSource,
    deleteSource,
    listSourceTypes,
    getDestination,
    createDestination,
    updateDestination,
    deleteDestination,
    listStreams,
    getStream,
    updateStreamSelection,
    startReplication,
    stopReplication,
    listExtractions,
    listLoads,
    getExtractionLogs,
    listNotifications,
    manageCustomEmail,
    managePostLoadHook,
    pushData,
    validateData,
  ],
  triggers: [
    postLoadTrigger,
    extractionStatusTrigger,
  ],
});
