import {
  Slate } from 'slates';
import { spec } from './spec';
import {
  listDashboards,
  getDashboard,
  createDashboard,
  updateDashboard,
  deleteDashboard,
  listKlips,
  getKlip,
  manageKlip,
  listDatasources,
  getDatasource,
  manageDatasource,
  refreshDatasource,
  getDatasourceInstanceData,
  listUsers,
  manageUser,
  listRoles,
  manageRole,
  listClients,
  manageClient,
  manageGroup,
  listPublishedLinks,
  managePublishedLink,
  getProfile,
} from './tools';
import {
  dashboardChanges,
  userChanges,
  datasourceChanges,
  inboundWebhook,
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    listDashboards,
    getDashboard,
    createDashboard,
    updateDashboard,
    deleteDashboard,
    listKlips,
    getKlip,
    manageKlip,
    listDatasources,
    getDatasource,
    manageDatasource,
    refreshDatasource,
    getDatasourceInstanceData,
    listUsers,
    manageUser,
    listRoles,
    manageRole,
    listClients,
    manageClient,
    manageGroup,
    listPublishedLinks,
    managePublishedLink,
    getProfile,
  ],
  triggers: [
    inboundWebhook,
    dashboardChanges,
    userChanges,
    datasourceChanges,
  ],
});
