import { Slate } from 'slates';
import { spec } from './spec';
import {
  createAddress,
  getAddress,
  listAddresses,
  deleteAddress,
  sendPostcard,
  getPostcard,
  listPostcards,
  cancelPostcard,
  sendLetter,
  getLetter,
  listLetters,
  cancelLetter,
  sendSelfMailer,
  getSelfMailer,
  cancelSelfMailer,
  sendCheck,
  getCheck,
  cancelCheck,
  createTemplate,
  getTemplate,
  listTemplates,
  updateTemplate,
  deleteTemplate,
  createTemplateVersion,
  verifyUSAddress,
  autocompleteUSAddress,
  verifyInternationalAddress,
  createBankAccount,
  verifyBankAccount,
  getBankAccount,
  listBankAccounts,
  deleteBankAccount,
  createCampaign,
  getCampaign,
  listCampaigns,
  updateCampaign,
  sendCampaign,
  deleteCampaign
} from './tools';
import { mailEvents } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    createAddress,
    getAddress,
    listAddresses,
    deleteAddress,
    sendPostcard,
    getPostcard,
    listPostcards,
    cancelPostcard,
    sendLetter,
    getLetter,
    listLetters,
    cancelLetter,
    sendSelfMailer,
    getSelfMailer,
    cancelSelfMailer,
    sendCheck,
    getCheck,
    cancelCheck,
    createTemplate,
    getTemplate,
    listTemplates,
    updateTemplate,
    deleteTemplate,
    createTemplateVersion,
    verifyUSAddress,
    autocompleteUSAddress,
    verifyInternationalAddress,
    createBankAccount,
    verifyBankAccount,
    getBankAccount,
    listBankAccounts,
    deleteBankAccount,
    createCampaign,
    getCampaign,
    listCampaigns,
    updateCampaign,
    sendCampaign,
    deleteCampaign
  ] as any,
  triggers: [mailEvents] as any
});
