import { Slate } from 'slates';
import { spec } from './spec';
import {
  createDid,
  listDids,
  getDid,
  deleteDid,
  issueCredential,
  listCredentials,
  getCredential,
  revokeCredential,
  createSchema,
  listSchemas,
  createRegistry,
  listRegistries,
  createProofTemplate,
  listProofTemplates,
  createProofRequest,
  getProofRequest,
  verifyCredential,
  manageProfile,
  listProfiles,
  getJob,
} from './tools';
import {
  credentialEvents,
  didEvents,
  registryEvents,
  schemaEvents,
  proofEvents,
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    createDid,
    listDids,
    getDid,
    deleteDid,
    issueCredential,
    listCredentials,
    getCredential,
    revokeCredential,
    createSchema,
    listSchemas,
    createRegistry,
    listRegistries,
    createProofTemplate,
    listProofTemplates,
    createProofRequest,
    getProofRequest,
    verifyCredential,
    manageProfile,
    listProfiles,
    getJob,
  ],
  triggers: [
    credentialEvents,
    didEvents,
    registryEvents,
    schemaEvents,
    proofEvents,
  ],
});
