import {
  Slate } from 'slates';
import { spec } from './spec';
import {
  runPipelineTool,
  bulkRunPipelineTool,
  controlPipelineRunTool,
  listPipelinesTool,
  getPipelineTool,
  deletePipelineTool,
  createKnowledgeBaseTool,
  listKnowledgeBasesTool,
  getKnowledgeBaseTool,
  deleteKnowledgeBaseTool,
  addDataToKnowledgeBaseTool,
  queryKnowledgeBaseTool,
  manageDocumentsTool,
  runChatbotTool,
  listChatbotsTool,
  getChatbotTool,
  createChatbotTool,
  deleteChatbotTool,
  terminateChatbotSessionTool,
  runTransformationTool,
  listTransformationsTool,
  getTransformationTool,
  createTransformationTool,
  deleteTransformationTool,
} from './tools';
import {
  pipelineChangesTrigger,
  knowledgeBaseChangesTrigger,
  chatbotChangesTrigger,
  transformationChangesTrigger,
  inboundWebhook,
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    runPipelineTool,
    bulkRunPipelineTool,
    controlPipelineRunTool,
    listPipelinesTool,
    getPipelineTool,
    deletePipelineTool,
    createKnowledgeBaseTool,
    listKnowledgeBasesTool,
    getKnowledgeBaseTool,
    deleteKnowledgeBaseTool,
    addDataToKnowledgeBaseTool,
    queryKnowledgeBaseTool,
    manageDocumentsTool,
    runChatbotTool,
    listChatbotsTool,
    getChatbotTool,
    createChatbotTool,
    deleteChatbotTool,
    terminateChatbotSessionTool,
    runTransformationTool,
    listTransformationsTool,
    getTransformationTool,
    createTransformationTool,
    deleteTransformationTool,
  ],
  triggers: [
    inboundWebhook,
    pipelineChangesTrigger,
    knowledgeBaseChangesTrigger,
    chatbotChangesTrigger,
    transformationChangesTrigger,
  ],
});
