import { Slate } from 'slates';
import { spec } from './spec';
import {
  listItems,
  getItem,
  createOrUpdateItem,
  deleteItem,
  listCustomers,
  createOrUpdateCustomer,
  deleteCustomer,
  listReceipts,
  getReceipt,
  createReceipt,
  createRefund,
  getInventory,
  updateInventory,
  listCategories,
  createOrUpdateCategory,
  deleteCategory,
  listDiscounts,
  createOrUpdateDiscount,
  deleteDiscount,
  listModifiers,
  createOrUpdateModifier,
  deleteModifier,
  listTaxes,
  createOrUpdateTax,
  deleteTax,
  listSuppliers,
  createOrUpdateSupplier,
  deleteSupplier,
  listEmployees,
  listStores,
  listShifts,
  listPaymentTypes,
  getMerchant,
} from './tools';
import {
  receiptEvents,
  itemEvents,
  inventoryEvents,
  customerEvents,
  shiftEvents,
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    listItems,
    getItem,
    createOrUpdateItem,
    deleteItem,
    listCustomers,
    createOrUpdateCustomer,
    deleteCustomer,
    listReceipts,
    getReceipt,
    createReceipt,
    createRefund,
    getInventory,
    updateInventory,
    listCategories,
    createOrUpdateCategory,
    deleteCategory,
    listDiscounts,
    createOrUpdateDiscount,
    deleteDiscount,
    listModifiers,
    createOrUpdateModifier,
    deleteModifier,
    listTaxes,
    createOrUpdateTax,
    deleteTax,
    listSuppliers,
    createOrUpdateSupplier,
    deleteSupplier,
    listEmployees,
    listStores,
    listShifts,
    listPaymentTypes,
    getMerchant,
  ],
  triggers: [
    receiptEvents,
    itemEvents,
    inventoryEvents,
    customerEvents,
    shiftEvents,
  ],
});
