import { Slate } from 'slates';
import { spec } from './spec';
import {
  listForms,
  getForm,
  updateForm,
  listFormFields,
  listSubmissions,
  getSubmission,
  deleteSubmission,
  listPartialSubmissions,
  listProducts,
  createProduct,
  updateProduct,
  deleteProduct,
  listCoupons,
  createCoupon,
  updateCoupon,
  deleteCoupon,
  listSpaces,
  createSpace,
  listSpaceForms,
  listPapersignDocuments,
  getPapersignDocument,
  sendPapersignDocument,
  copyPapersignDocument,
  movePapersignDocument,
  cancelPapersignDocument,
  listPapersignFolders,
  createPapersignFolder,
} from './tools';
import {
  formSubmissionTrigger,
  papersignEventTrigger,
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    listForms,
    getForm,
    updateForm,
    listFormFields,
    listSubmissions,
    getSubmission,
    deleteSubmission,
    listPartialSubmissions,
    listProducts,
    createProduct,
    updateProduct,
    deleteProduct,
    listCoupons,
    createCoupon,
    updateCoupon,
    deleteCoupon,
    listSpaces,
    createSpace,
    listSpaceForms,
    listPapersignDocuments,
    getPapersignDocument,
    sendPapersignDocument,
    copyPapersignDocument,
    movePapersignDocument,
    cancelPapersignDocument,
    listPapersignFolders,
    createPapersignFolder,
  ],
  triggers: [
    formSubmissionTrigger,
    papersignEventTrigger,
  ],
});
