import {
  Slate } from 'slates';
import { spec } from './spec';
import {
  sendMessage,
  editMessage,
  deleteMessages,
  fetchMessages,
  searchMessages,
  manageReactions,
  pinMessage,
  createServer,
  fetchServer,
  editServer,
  deleteServer,
  createChannel,
  fetchChannel,
  editChannel,
  deleteChannel,
  fetchMembers,
  editMember,
  kickMember,
  manageBan,
  fetchUser,
  openDM,
  createRole,
  editRole,
  deleteRole,
  createWebhook,
  fetchWebhooks,
  executeWebhook,
  fetchServerEmoji,
  deleteEmoji,
  createInvite,
  fetchInvite,
  deleteInvite,
  fetchServerInvites,
} from './tools';
import {
  newMessage,
  channelMessage,
  serverMemberChanges,
  inboundWebhook,
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    sendMessage,
    editMessage,
    deleteMessages,
    fetchMessages,
    searchMessages,
    manageReactions,
    pinMessage,
    createServer,
    fetchServer,
    editServer,
    deleteServer,
    createChannel,
    fetchChannel,
    editChannel,
    deleteChannel,
    fetchMembers,
    editMember,
    kickMember,
    manageBan,
    fetchUser,
    openDM,
    createRole,
    editRole,
    deleteRole,
    createWebhook,
    fetchWebhooks,
    executeWebhook,
    fetchServerEmoji,
    deleteEmoji,
    createInvite,
    fetchInvite,
    deleteInvite,
    fetchServerInvites,
  ],
  triggers: [
    inboundWebhook,
    newMessage,
    channelMessage,
    serverMemberChanges,
  ],
});
