import { Slate } from 'slates';
import { spec } from './spec';
import {
  listScripts,
  getScript,
  deleteScript,
  listVersions,
  getVersion,
  listDeployments,
  createDeployment,
  listSecrets,
  putSecret,
  deleteSecret,
  getWorkerSettings,
  updateScriptSettings,
  getSchedules,
  updateSchedules,
  listDomains,
  attachDomain,
  detachDomain,
  listRoutes,
  createRoute,
  updateRoute,
  deleteRoute,
  getSubdomain,
  setScriptSubdomain,
  createTail,
  listTails,
  deleteTail,
  queryTelemetry,
  listTelemetryKeys
} from './tools';
import { scriptChanges, deploymentChanges, inboundWebhook } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    listScripts,
    getScript,
    deleteScript,
    listVersions,
    getVersion,
    listDeployments,
    createDeployment,
    listSecrets,
    putSecret,
    deleteSecret,
    getWorkerSettings,
    updateScriptSettings,
    getSchedules,
    updateSchedules,
    listDomains,
    attachDomain,
    detachDomain,
    listRoutes,
    createRoute,
    updateRoute,
    deleteRoute,
    getSubdomain,
    setScriptSubdomain,
    createTail,
    listTails,
    deleteTail,
    queryTelemetry,
    listTelemetryKeys
  ],
  triggers: [inboundWebhook, scriptChanges, deploymentChanges]
});
