import {
  Slate } from 'slates';
import { spec } from './spec';
import {
  createInvoice,
  getInvoice,
  updateInvoice,
  listInvoices,
  invoiceActions,
  estimateActions,
  manageContact,
  listContacts,
  manageEstimate,
  listEstimates,
  manageExpense,
  listExpenses,
  managePayment,
  listPayments,
  manageCreditNote,
  listCreditNotes,
  manageProject,
  listProjects,
  manageItem,
  listItems,
  manageTimeEntry,
  manageRecurringInvoice,
} from './tools';
import {
  newInvoice,
  updatedInvoice,
  newContact,
  newEstimate,
  newExpense,
  newPayment,
  inboundWebhook,
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    createInvoice,
    getInvoice,
    updateInvoice,
    listInvoices,
    invoiceActions,
    estimateActions,
    manageContact,
    listContacts,
    manageEstimate,
    listEstimates,
    manageExpense,
    listExpenses,
    managePayment,
    listPayments,
    manageCreditNote,
    listCreditNotes,
    manageProject,
    listProjects,
    manageItem,
    listItems,
    manageTimeEntry,
    manageRecurringInvoice,
  ],
  triggers: [
    inboundWebhook,
    newInvoice,
    updatedInvoice,
    newContact,
    newEstimate,
    newExpense,
    newPayment,
  ],
});
