import { Slate } from 'slates';
import { spec } from './spec';
import {
  listDroplets,
  createDroplet,
  deleteDroplet,
  performDropletAction,
  listDatabases,
  createDatabase,
  deleteDatabase,
  manageDatabaseUsers,
  listDomains,
  createDomain,
  manageDNSRecords,
  listKubernetesClusters,
  createKubernetesCluster,
  deleteKubernetesCluster,
  getKubeconfig,
  manageNodePools,
  listApps,
  getApp,
  deployApp,
  deleteApp,
  listVolumes,
  createVolume,
  manageVolumeAttachment,
  deleteVolume,
  listLoadBalancers,
  manageFirewall,
  manageVPC,
  manageReservedIPs,
  listProjects,
  manageProject,
  manageProjectResources,
  manageSSHKeys,
  listAlertPolicies,
  manageUptimeChecks,
  getAccount,
  getBilling,
  listRegions,
  listSizes,
  listSnapshots,
  listImages,
  manageContainerRegistry,
  manageTags
} from './tools';

import { inboundWebhook } from './triggers/inbound-webhook';

export let provider = Slate.create({
  spec,
  tools: [
    listDroplets,
    createDroplet,
    deleteDroplet,
    performDropletAction,
    listDatabases,
    createDatabase,
    deleteDatabase,
    manageDatabaseUsers,
    listDomains,
    createDomain,
    manageDNSRecords,
    listKubernetesClusters,
    createKubernetesCluster,
    deleteKubernetesCluster,
    getKubeconfig,
    manageNodePools,
    listApps,
    getApp,
    deployApp,
    deleteApp,
    listVolumes,
    createVolume,
    manageVolumeAttachment,
    deleteVolume,
    listLoadBalancers,
    manageFirewall,
    manageVPC,
    manageReservedIPs,
    listProjects,
    manageProject,
    manageProjectResources,
    manageSSHKeys,
    listAlertPolicies,
    manageUptimeChecks,
    getAccount,
    getBilling,
    listRegions,
    listSizes,
    listSnapshots,
    listImages,
    manageContainerRegistry,
    manageTags
  ],
  triggers: [inboundWebhook]
});
