import {
  Slate } from 'slates';
import { spec } from './spec';
import {
  listProjects,
  createProject,
  getProject,
  listNotes,
  getNote,
  manageNote,
  listData,
  manageData,
  listInsights,
  getInsight,
  manageInsight,
  listHighlights,
  listTags,
  listContacts,
  manageContact,
  listDocs,
  getDoc,
  manageDoc,
  listChannels,
  manageChannel,
  manageTopic,
  addChannelDataPoint,
  browseFolders,
  search,
  summarize,
  importFile,
  getFile,
} from './tools';
import {
  newNotes,
  newInsights,
  newProjects,
  inboundWebhook,
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    listProjects,
    createProject,
    getProject,
    listNotes,
    getNote,
    manageNote,
    listData,
    manageData,
    listInsights,
    getInsight,
    manageInsight,
    listHighlights,
    listTags,
    listContacts,
    manageContact,
    listDocs,
    getDoc,
    manageDoc,
    listChannels,
    manageChannel,
    manageTopic,
    addChannelDataPoint,
    browseFolders,
    search,
    summarize,
    importFile,
    getFile,
  ],
  triggers: [
    inboundWebhook,
    newNotes,
    newInsights,
    newProjects,
  ],
});
