import {
  Slate } from 'slates';
import { spec } from './spec';
import {
  listCustomers,
  getCustomer,
  createCustomer,
  updateCustomer,
  deleteCustomer,
  listContacts,
  createContact,
  listProjects,
  createProject,
  updateProject,
  listTasks,
  createTask,
  updateTask,
  listTransactions,
  createTransaction,
  listOffers,
  createOffer,
  createAgreement,
  listProducts,
  createProduct,
  updateProduct,
  listSalesOpportunities,
  createSalesOpportunity,
  listSalesNotes,
  createSalesNote,
  listTimeEntries,
  createTimeEntry,
  listEmails,
  listDocuments,
  listWarehouseDocuments,
} from './tools';
import {
  customerChanges,
  taskChanges,
  transactionChanges,
  salesOpportunityChanges,
  inboundWebhook,
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    listCustomers,
    getCustomer,
    createCustomer,
    updateCustomer,
    deleteCustomer,
    listContacts,
    createContact,
    listProjects,
    createProject,
    updateProject,
    listTasks,
    createTask,
    updateTask,
    listTransactions,
    createTransaction,
    listOffers,
    createOffer,
    createAgreement,
    listProducts,
    createProduct,
    updateProduct,
    listSalesOpportunities,
    createSalesOpportunity,
    listSalesNotes,
    createSalesNote,
    listTimeEntries,
    createTimeEntry,
    listEmails,
    listDocuments,
    listWarehouseDocuments,
  ],
  triggers: [
    inboundWebhook,
    customerChanges,
    taskChanges,
    transactionChanges,
    salesOpportunityChanges,
  ],
});
