import { Slate } from 'slates';
import { spec } from './spec';
import {
  manageProspect,
  getProspect,
  listProspects,
  manageAccount,
  listAccounts,
  manageSequence,
  listSequences,
  manageSequenceState,
  listMailings,
  manageTask,
  listTasks,
  manageOpportunity,
  listOpportunities,
  manageTemplate,
  manageSnippet,
  createCall,
  listUsers,
} from './tools';
import {
  prospectEvents,
  accountEvents,
  mailingEvents,
  sequenceEvents,
  sequenceStateEvents,
  taskEvents,
  opportunityEvents,
  callEvents,
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    manageProspect,
    getProspect,
    listProspects,
    manageAccount,
    listAccounts,
    manageSequence,
    listSequences,
    manageSequenceState,
    listMailings,
    manageTask,
    listTasks,
    manageOpportunity,
    listOpportunities,
    manageTemplate,
    manageSnippet,
    createCall,
    listUsers,
  ],
  triggers: [
    prospectEvents,
    accountEvents,
    mailingEvents,
    sequenceEvents,
    sequenceStateEvents,
    taskEvents,
    opportunityEvents,
    callEvents,
  ],
});
