import { Slate } from 'slates';
import { spec } from './spec';

import {
  searchPersons,
  getPerson,
  createPerson,
  updatePerson,
  deletePerson,
  searchOrganizations,
  getOrganization,
  createOrganization,
  updateOrganization,
  deleteOrganization,
  searchOpportunities,
  getOpportunity,
  createOpportunity,
  updateOpportunity,
  deleteOpportunity,
  getLists,
  getListEntries,
  addListEntry,
  removeListEntry,
  listNotes,
  createNote,
  updateNote,
  deleteNote,
  getInteractions,
  getFields,
  getFieldValues,
  setFieldValue,
  updateFieldValue,
  deleteFieldValue,
  getFieldValueChanges,
  listReminders,
  createReminder,
  updateReminder,
  deleteReminder,
  getRelationshipStrengths,
  getEntityFiles
} from './tools';

import {
  personEvents,
  organizationEvents,
  opportunityEvents,
  listEvents,
  listEntryEvents,
  fieldValueEvents,
  noteEvents,
  fileEvents,
  reminderEvents
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    searchPersons,
    getPerson,
    createPerson,
    updatePerson,
    deletePerson,
    searchOrganizations,
    getOrganization,
    createOrganization,
    updateOrganization,
    deleteOrganization,
    searchOpportunities,
    getOpportunity,
    createOpportunity,
    updateOpportunity,
    deleteOpportunity,
    getLists,
    getListEntries,
    addListEntry,
    removeListEntry,
    listNotes,
    createNote,
    updateNote,
    deleteNote,
    getInteractions,
    getFields,
    getFieldValues,
    setFieldValue,
    updateFieldValue,
    deleteFieldValue,
    getFieldValueChanges,
    listReminders,
    createReminder,
    updateReminder,
    deleteReminder,
    getRelationshipStrengths,
    getEntityFiles
  ],
  triggers: [
    personEvents,
    organizationEvents,
    opportunityEvents,
    listEvents,
    listEntryEvents,
    fieldValueEvents,
    noteEvents,
    fileEvents,
    reminderEvents
  ]
});
