import {
  Slate } from 'slates';
import { spec } from './spec';

import {
  listContacts,
  getContact,
  createContact,
  updateContact,
  deleteContact,
  listInvoices,
  getInvoice,
  createInvoice,
  updateInvoice,
  deleteInvoice,
  emailInvoice,
  listExpenses,
  createExpense,
  updateExpense,
  deleteExpense,
  listProjects,
  createProject,
  updateProject,
  deleteProject,
  listTimeslips,
  createTimeslip,
  updateTimeslip,
  deleteTimeslip,
  listBankAccounts,
  listBankTransactions,
  listBills,
  createBill,
  listEstimates,
  createEstimate,
  listTasks,
  createTask,
  listCreditNotes,
  getProfitAndLoss,
  getBalanceSheet,
  getTrialBalance,
  getCompany,
  listUsers,
  listCategories,
} from './tools';

import {
  invoiceChanges,
  contactChanges,
  expenseChanges,
  billChanges,
  projectChanges,
  inboundWebhook,
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    listContacts,
    getContact,
    createContact,
    updateContact,
    deleteContact,
    listInvoices,
    getInvoice,
    createInvoice,
    updateInvoice,
    deleteInvoice,
    emailInvoice,
    listExpenses,
    createExpense,
    updateExpense,
    deleteExpense,
    listProjects,
    createProject,
    updateProject,
    deleteProject,
    listTimeslips,
    createTimeslip,
    updateTimeslip,
    deleteTimeslip,
    listBankAccounts,
    listBankTransactions,
    listBills,
    createBill,
    listEstimates,
    createEstimate,
    listTasks,
    createTask,
    listCreditNotes,
    getProfitAndLoss,
    getBalanceSheet,
    getTrialBalance,
    getCompany,
    listUsers,
    listCategories,
  ],
  triggers: [
    inboundWebhook,
    invoiceChanges,
    contactChanges,
    expenseChanges,
    billChanges,
    projectChanges,
  ],
});
