import {
  Slate } from 'slates';
import { spec } from './spec';

import {
  createContact,
  getContact,
  updateContact,
  deleteContact,
  createProject,
  getProject,
  updateProject,
  createTask,
  getTask,
  updateTask,
  createInvoice,
  getInvoice,
  createEstimate,
  getEstimate,
  createContract,
  getContract,
  createEmployee,
  getEmployee,
  createTicket,
  getTicket,
  createProduct,
  getProduct,
  createDeal,
  getDeal,
  getUser,
  createTimeEntry,
  createExpense,
} from './tools';

import {
  newContactTrigger,
  newProjectTrigger,
  newTaskTrigger,
  newInvoiceTrigger,
  newEstimateTrigger,
  newContractTrigger,
  newEmployeeTrigger,
  newTicketTrigger,
  newProductTrigger,
  inboundWebhook,
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    createContact,
    getContact,
    updateContact,
    deleteContact,
    createProject,
    getProject,
    updateProject,
    createTask,
    getTask,
    updateTask,
    createInvoice,
    getInvoice,
    createEstimate,
    getEstimate,
    createContract,
    getContract,
    createEmployee,
    getEmployee,
    createTicket,
    getTicket,
    createProduct,
    getProduct,
    createDeal,
    getDeal,
    getUser,
    createTimeEntry,
    createExpense,
  ],
  triggers: [
    inboundWebhook,
    newContactTrigger,
    newProjectTrigger,
    newTaskTrigger,
    newInvoiceTrigger,
    newEstimateTrigger,
    newContractTrigger,
    newEmployeeTrigger,
    newTicketTrigger,
    newProductTrigger,
  ],
});
