import { Slate } from 'slates';
import { spec } from './spec';
import {
  writeData,
  queryData,
  deleteData,
  listBuckets,
  createBucket,
  updateBucket,
  deleteBucket,
  listTasks,
  getTask,
  createTask,
  updateTask,
  deleteTask,
  runTask,
  getTaskRuns,
  listAuthorizations,
  createAuthorization,
  updateAuthorization,
  deleteAuthorization,
  listLabels,
  createLabel,
  updateLabel,
  deleteLabel,
  listDashboards,
  createDashboard,
  updateDashboard,
  deleteDashboard,
  listSecrets,
  upsertSecrets,
  deleteSecrets,
  listTelegrafs,
  getTelegraf,
  createTelegraf,
  updateTelegraf,
  deleteTelegraf,
  listChecks,
  listNotificationEndpoints,
  listNotificationRules,
  listOrganizations,
  getOrganizationMembers,
  listDBRPs,
  createDBRP,
  deleteDBRP
} from './tools';
import { taskRunsTrigger, bucketChangesTrigger, inboundWebhook } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    writeData,
    queryData,
    deleteData,
    listBuckets,
    createBucket,
    updateBucket,
    deleteBucket,
    listTasks,
    getTask,
    createTask,
    updateTask,
    deleteTask,
    runTask,
    getTaskRuns,
    listAuthorizations,
    createAuthorization,
    updateAuthorization,
    deleteAuthorization,
    listLabels,
    createLabel,
    updateLabel,
    deleteLabel,
    listDashboards,
    createDashboard,
    updateDashboard,
    deleteDashboard,
    listSecrets,
    upsertSecrets,
    deleteSecrets,
    listTelegrafs,
    getTelegraf,
    createTelegraf,
    updateTelegraf,
    deleteTelegraf,
    listChecks,
    listNotificationEndpoints,
    listNotificationRules,
    listOrganizations,
    getOrganizationMembers,
    listDBRPs,
    createDBRP,
    deleteDBRP
  ],
  triggers: [inboundWebhook, taskRunsTrigger, bucketChangesTrigger]
});
