import { Slate } from '@slates/provider';
import { spec } from './spec';
import {
  searchPeople,
  searchOrganizations,
  getOrganization,
  enrichOrganization,
  listOrganizationJobPostings,
  enrichPerson,
  searchContacts,
  createContact,
  updateContact,
  bulkCreateContacts,
  bulkUpdateContacts,
  updateContactStages,
  updateContactOwners,
  searchAccounts,
  getAccount,
  createAccount,
  updateAccount,
  bulkCreateAccounts,
  bulkUpdateAccounts,
  updateAccountOwners,
  listDeals,
  getDeal,
  createDeal,
  updateDeal,
  searchSequences,
  addContactsToSequence,
  updateContactSequenceStatus,
  searchTasks,
  createTask,
  searchCalls,
  createCall,
  updateCall,
  searchConversations,
  getConversation,
  exportConversations,
  queryAnalyticsReport,
  listUsers,
  listStages,
  listEmailAccounts,
  getUsageStats
} from './tools';
import { contactChanges, dealChanges, inboundWebhook } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    searchPeople,
    searchOrganizations,
    getOrganization,
    enrichOrganization,
    listOrganizationJobPostings,
    enrichPerson,
    searchContacts,
    createContact,
    updateContact,
    bulkCreateContacts,
    bulkUpdateContacts,
    updateContactStages,
    updateContactOwners,
    searchAccounts,
    getAccount,
    createAccount,
    updateAccount,
    bulkCreateAccounts,
    bulkUpdateAccounts,
    updateAccountOwners,
    listDeals,
    getDeal,
    createDeal,
    updateDeal,
    searchSequences,
    addContactsToSequence,
    updateContactSequenceStatus,
    searchTasks,
    createTask,
    searchCalls,
    createCall,
    updateCall,
    searchConversations,
    getConversation,
    exportConversations,
    queryAnalyticsReport,
    listUsers,
    listStages,
    listEmailAccounts,
    getUsageStats
  ],
  triggers: [inboundWebhook, contactChanges, dealChanges]
});
