import {
  Slate } from 'slates';
import { spec } from './spec';

import {
  createContact,
  getContact,
  updateContact,
  deleteContact,
  searchContacts,
  createCompany,
  getCompany,
  updateCompany,
  deleteCompany,
  searchCompanies,
  createDeal,
  getDeal,
  updateDeal,
  deleteDeal,
  searchDeals,
  createActivity,
  getActivity,
  updateActivity,
  deleteActivity,
  searchActivities,
  createProduct,
  getProduct,
  updateProduct,
  deleteProduct,
  searchProducts,
  createTicket,
  getTicket,
  updateTicket,
  deleteTicket,
  searchTickets,
  createNote,
  getNote,
  updateNote,
  deleteNote,
  listUsers,
  getUser,
} from './tools';

import {
  contactEvents,
  companyEvents,
  dealEvents,
  activityEvents,
  inboundWebhook,
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    createContact,
    getContact,
    updateContact,
    deleteContact,
    searchContacts,
    createCompany,
    getCompany,
    updateCompany,
    deleteCompany,
    searchCompanies,
    createDeal,
    getDeal,
    updateDeal,
    deleteDeal,
    searchDeals,
    createActivity,
    getActivity,
    updateActivity,
    deleteActivity,
    searchActivities,
    createProduct,
    getProduct,
    updateProduct,
    deleteProduct,
    searchProducts,
    createTicket,
    getTicket,
    updateTicket,
    deleteTicket,
    searchTickets,
    createNote,
    getNote,
    updateNote,
    deleteNote,
    listUsers,
    getUser,
  ],
  triggers: [
    inboundWebhook,
    contactEvents,
    companyEvents,
    dealEvents,
    activityEvents,
  ],
});
