import { Slate } from 'slates';
import { spec } from './spec';
import {
  createTicket,
  getTicket,
  listTickets,
  updateTicket,
  deleteTicket,
  searchTickets,
  addTicketConversation,
  createProblem,
  getProblem,
  listProblems,
  updateProblem,
  deleteProblem,
  createChange,
  getChange,
  listChanges,
  updateChange,
  deleteChange,
  createAsset,
  getAsset,
  listAssets,
  updateAsset,
  deleteAsset,
  createRequester,
  getRequester,
  listRequesters,
  updateRequester,
  listAgents,
  getAgent,
  listKnowledgeBaseArticles,
  getKnowledgeBaseArticle,
  createKnowledgeBaseArticle,
  updateKnowledgeBaseArticle,
  listKnowledgeBaseCategories,
  listKnowledgeBaseFolders,
  listServiceCatalogItems,
  getServiceCatalogItem,
  placeServiceRequest,
  listServiceCategories,
  listDepartments,
  getDepartment
} from './tools';
import { ticketUpdates, changeUpdates, inboundWebhook } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    createTicket,
    getTicket,
    listTickets,
    updateTicket,
    deleteTicket,
    searchTickets,
    addTicketConversation,
    createProblem,
    getProblem,
    listProblems,
    updateProblem,
    deleteProblem,
    createChange,
    getChange,
    listChanges,
    updateChange,
    deleteChange,
    createAsset,
    getAsset,
    listAssets,
    updateAsset,
    deleteAsset,
    createRequester,
    getRequester,
    listRequesters,
    updateRequester,
    listAgents,
    getAgent,
    listKnowledgeBaseArticles,
    getKnowledgeBaseArticle,
    createKnowledgeBaseArticle,
    updateKnowledgeBaseArticle,
    listKnowledgeBaseCategories,
    listKnowledgeBaseFolders,
    listServiceCatalogItems,
    getServiceCatalogItem,
    placeServiceRequest,
    listServiceCategories,
    listDepartments,
    getDepartment
  ],
  triggers: [inboundWebhook, ticketUpdates, changeUpdates]
});
