import { Slate } from 'slates';
import { spec } from './spec';
import {
  listSites,
  getSite,
  publishSite,
  listCollections,
  getCollection,
  listCollectionItems,
  manageCollectionItem,
  publishCollectionItems,
  listPages,
  updatePageSettings,
  listFormSubmissions,
  listProducts,
  manageProduct,
  listOrders,
  updateOrder,
  manageInventory,
  listUsers,
  manageUser,
  listAssets,
} from './tools';
import {
  formSubmissionTrigger,
  sitePublishTrigger,
  pageEventsTrigger,
  ecommerceEventsTrigger,
  userAccountEventsTrigger,
  collectionItemEventsTrigger,
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    listSites,
    getSite,
    publishSite,
    listCollections,
    getCollection,
    listCollectionItems,
    manageCollectionItem,
    publishCollectionItems,
    listPages,
    updatePageSettings,
    listFormSubmissions,
    listProducts,
    manageProduct,
    listOrders,
    updateOrder,
    manageInventory,
    listUsers,
    manageUser,
    listAssets,
  ],
  triggers: [
    formSubmissionTrigger,
    sitePublishTrigger,
    pageEventsTrigger,
    ecommerceEventsTrigger,
    userAccountEventsTrigger,
    collectionItemEventsTrigger,
  ],
});
