import { Slate } from 'slates';
import { spec } from './spec';
import {
  listContacts,
  getContact,
  createContact,
  updateContact,
  listSalesInvoices,
  getSalesInvoice,
  createSalesInvoice,
  manageSalesInvoice,
  manageRecurringInvoices,
  listEstimates,
  createEstimate,
  manageEstimate,
  manageProducts,
  manageLedgerAccounts,
  listTaxRates,
  manageTimeEntries,
  manageProjects,
  listFinancialMutations,
  linkBooking,
} from './tools';
import {
  contactEvents,
  salesInvoiceEvents,
  estimateEvents,
  paymentEvents,
  documentEvents,
  recurringInvoiceEvents,
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    listContacts,
    getContact,
    createContact,
    updateContact,
    listSalesInvoices,
    getSalesInvoice,
    createSalesInvoice,
    manageSalesInvoice,
    manageRecurringInvoices,
    listEstimates,
    createEstimate,
    manageEstimate,
    manageProducts,
    manageLedgerAccounts,
    listTaxRates,
    manageTimeEntries,
    manageProjects,
    listFinancialMutations,
    linkBooking,
  ] as any,
  triggers: [
    contactEvents,
    salesInvoiceEvents,
    estimateEvents,
    paymentEvents,
    documentEvents,
    recurringInvoiceEvents,
  ] as any,
});
