import { Slate } from 'slates';
import { spec } from './spec';
import {
  createCandidate,
  getCandidate,
  updateCandidate,
  deleteCandidate,
  searchCandidates,
  listCandidates,
  createJob,
  getJob,
  updateJob,
  deleteJob,
  searchJobs,
  createCompany,
  getCompany,
  updateCompany,
  searchCompanies,
  createContact,
  getContact,
  updateContact,
  searchContacts,
  createPipeline,
  getPipeline,
  updatePipelineStatus,
  deletePipeline,
  logActivity,
  getActivity,
  listActivities,
  createTask,
  getTask,
  updateTask,
  listTasks,
  listUsers,
  manageTags
} from './tools';
import {
  candidateEvents,
  jobEvents,
  contactEvents,
  companyEvents,
  pipelineEvents,
  activityEvents
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    createCandidate,
    getCandidate,
    updateCandidate,
    deleteCandidate,
    searchCandidates,
    listCandidates,
    createJob,
    getJob,
    updateJob,
    deleteJob,
    searchJobs,
    createCompany,
    getCompany,
    updateCompany,
    searchCompanies,
    createContact,
    getContact,
    updateContact,
    searchContacts,
    createPipeline,
    getPipeline,
    updatePipelineStatus,
    deletePipeline,
    logActivity,
    getActivity,
    listActivities,
    createTask,
    getTask,
    updateTask,
    listTasks,
    listUsers,
    manageTags
  ],
  triggers: [
    candidateEvents,
    jobEvents,
    contactEvents,
    companyEvents,
    pipelineEvents,
    activityEvents
  ]
});
