import { Slate } from 'slates';
import { spec } from './spec';
import {
  listCampaigns,
  getCampaign,
  createCampaign,
  updateCampaign,
  deleteCampaign,
  listContacts,
  getContact,
  createContact,
  updateContact,
  listTransactions,
  getTransaction,
  createTransaction,
  listFunds,
  createFund,
  updateFund,
  deleteFund,
  listPlans,
  getPlan,
  listTickets,
  getTicket,
  listPayouts,
  getPayout,
  listCampaignMembers,
  listCampaignTeams,
} from './tools';
import {
  campaignEvents,
  transactionEvents,
  contactEvents,
  ticketEvents,
  planEvents,
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    listCampaigns,
    getCampaign,
    createCampaign,
    updateCampaign,
    deleteCampaign,
    listContacts,
    getContact,
    createContact,
    updateContact,
    listTransactions,
    getTransaction,
    createTransaction,
    listFunds,
    createFund,
    updateFund,
    deleteFund,
    listPlans,
    getPlan,
    listTickets,
    getTicket,
    listPayouts,
    getPayout,
    listCampaignMembers,
    listCampaignTeams,
  ],
  triggers: [
    campaignEvents,
    transactionEvents,
    contactEvents,
    ticketEvents,
    planEvents,
  ],
});
