import { Slate } from 'slates';
import { spec } from './spec';
import {
  createInquiry,
  getInquiry,
  listInquiries,
  approveInquiry,
  declineInquiry,
  resumeInquiry,
  generateInquiryLink,
  tagInquiry,
  redactInquiry,
  createAccount,
  getAccount,
  listAccounts,
  updateAccount,
  consolidateAccounts,
  tagAccount,
  redactAccount,
  getVerification,
  listVerifications,
  redactVerification,
  createReport,
  getReport,
  listReports,
  createTransaction,
  getTransaction,
  listTransactions,
  tagTransaction,
  createCase,
  getCase,
  listCases,
  updateCase,
  listLists,
  getListItems,
  createListItem,
  archiveListItem,
  listEvents,
  getEvent
} from './tools';
import {
  inquiryEvents,
  accountEvents,
  verificationEvents,
  reportEvents,
  transactionEvents,
  caseEvents
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    createInquiry,
    getInquiry,
    listInquiries,
    approveInquiry,
    declineInquiry,
    resumeInquiry,
    generateInquiryLink,
    tagInquiry,
    redactInquiry,
    createAccount,
    getAccount,
    listAccounts,
    updateAccount,
    consolidateAccounts,
    tagAccount,
    redactAccount,
    getVerification,
    listVerifications,
    redactVerification,
    createReport,
    getReport,
    listReports,
    createTransaction,
    getTransaction,
    listTransactions,
    tagTransaction,
    createCase,
    getCase,
    listCases,
    updateCase,
    listLists,
    getListItems,
    createListItem,
    archiveListItem,
    listEvents,
    getEvent
  ],
  triggers: [
    inquiryEvents,
    accountEvents,
    verificationEvents,
    reportEvents,
    transactionEvents,
    caseEvents
  ]
});
