import { Slate } from 'slates';
import { spec } from './spec';
import {
  analyzeText,
  detectLanguage,
  listApps,
  getApp,
  createApp,
  updateApp,
  deleteApp,
  listAppTags,
  createAppTag,
  deleteAppTag,
  listIntents,
  getIntent,
  createIntent,
  deleteIntent,
  listEntities,
  getEntity,
  createEntity,
  updateEntity,
  deleteEntity,
  manageEntityKeywords,
  listTraits,
  getTrait,
  createTrait,
  deleteTrait,
  manageTraitValues,
  listUtterances,
  trainUtterances,
  deleteUtterances,
  exportApp,
  listVoices
} from './tools';

import { inboundWebhook } from './triggers/inbound-webhook';

export let provider = Slate.create({
  spec,
  tools: [
    analyzeText,
    detectLanguage,
    listApps,
    getApp,
    createApp,
    updateApp,
    deleteApp,
    listAppTags,
    createAppTag,
    deleteAppTag,
    listIntents,
    getIntent,
    createIntent,
    deleteIntent,
    listEntities,
    getEntity,
    createEntity,
    updateEntity,
    deleteEntity,
    manageEntityKeywords,
    listTraits,
    getTrait,
    createTrait,
    deleteTrait,
    manageTraitValues,
    listUtterances,
    trainUtterances,
    deleteUtterances,
    exportApp,
    listVoices
  ],
  triggers: [inboundWebhook]
});
