import { Slate } from 'slates';
import { spec } from './spec';
import {
  listOrganizations,
  listPeople,
  getPerson,
  createPerson,
  updatePerson,
  deletePerson,
  listProfileNotes,
  createProfileNote,
  updateProfileNote,
  deleteProfileNote,
  listFamilies,
  getFamily,
  createFamily,
  deleteFamily,
  manageFamilyMembers,
  listGroups,
  getGroupMembers,
  manageGroupMembership,
  listContributions,
  createContribution,
  deleteContribution,
  listCampaigns,
  listPledges,
} from './tools';
import {
  peopleEvents,
  contributionEvents,
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    listOrganizations,
    listPeople,
    getPerson,
    createPerson,
    updatePerson,
    deletePerson,
    listProfileNotes,
    createProfileNote,
    updateProfileNote,
    deleteProfileNote,
    listFamilies,
    getFamily,
    createFamily,
    deleteFamily,
    manageFamilyMembers,
    listGroups,
    getGroupMembers,
    manageGroupMembership,
    listContributions,
    createContribution,
    deleteContribution,
    listCampaigns,
    listPledges,
  ],
  triggers: [
    peopleEvents,
    contributionEvents,
  ],
});
