import { Slate } from 'slates';
import { spec } from './spec';
import {
  listAccounts,
  getAccount,
  createAccount,
  updateAccount,
  deleteAccount,
  listContacts,
  getContact,
  createContact,
  updateContact,
  deleteContact,
  listOpportunities,
  getOpportunity,
  createOpportunity,
  updateOpportunity,
  deleteOpportunity,
  listTasks,
  createTask,
  updateTask,
  deleteTask,
  createNote,
  updateNote,
  deleteNote,
  logMeeting,
  logCall,
  listTags,
  createTag,
  updateTag,
  deleteTag,
  listPipelines,
  listUsers,
  getMe,
  listWorkflows,
  getWorkflow,
  listCurrencies
} from './tools';
import { contactChanges, inboundWebhook } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    listAccounts,
    getAccount,
    createAccount,
    updateAccount,
    deleteAccount,
    listContacts,
    getContact,
    createContact,
    updateContact,
    deleteContact,
    listOpportunities,
    getOpportunity,
    createOpportunity,
    updateOpportunity,
    deleteOpportunity,
    listTasks,
    createTask,
    updateTask,
    deleteTask,
    createNote,
    updateNote,
    deleteNote,
    logMeeting,
    logCall,
    listTags,
    createTag,
    updateTag,
    deleteTag,
    listPipelines,
    listUsers,
    getMe,
    listWorkflows,
    getWorkflow,
    listCurrencies
  ],
  triggers: [inboundWebhook, contactChanges]
});
