import { Slate } from 'slates';
import { spec } from './spec';
import {
  sendEmail,
  listDomains,
  getDomain,
  createDomain,
  deleteDomain,
  verifyDomain,
  getDomainTracking,
  updateDomainTracking,
  getEvents,
  listSuppressions,
  addSuppression,
  removeSuppression,
  listMailingLists,
  createMailingList,
  updateMailingList,
  deleteMailingList,
  listMailingListMembers,
  addMailingListMember,
  removeMailingListMember,
  listTemplates,
  getTemplate,
  createTemplate,
  deleteTemplate,
  createTemplateVersion,
  listRoutes,
  createRoute,
  updateRoute,
  deleteRoute,
  validateEmail,
  getStats,
  listWebhooks,
  createWebhook,
  deleteWebhook
} from './tools';
import { emailEvents } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    sendEmail,
    listDomains,
    getDomain,
    createDomain,
    deleteDomain,
    verifyDomain,
    getDomainTracking,
    updateDomainTracking,
    getEvents,
    listSuppressions,
    addSuppression,
    removeSuppression,
    listMailingLists,
    createMailingList,
    updateMailingList,
    deleteMailingList,
    listMailingListMembers,
    addMailingListMember,
    removeMailingListMember,
    listTemplates,
    getTemplate,
    createTemplate,
    deleteTemplate,
    createTemplateVersion,
    listRoutes,
    createRoute,
    updateRoute,
    deleteRoute,
    validateEmail,
    getStats,
    listWebhooks,
    createWebhook,
    deleteWebhook
  ],
  triggers: [emailEvents]
});
