import { Slate } from 'slates';
import { spec } from './spec';
import {
  getEmployee,
  getEmployeeDirectory,
  createEmployee,
  updateEmployee,
  getTableData,
  upsertTableRow,
  deleteTableRow,
  getTimeOffRequests,
  createTimeOffRequest,
  updateTimeOffRequestStatus,
  getWhosOut,
  getTimeOffBalances,
  getTimeOffTypes,
  getTimesheetEntries,
  clockInOut,
  addTimesheetEntry,
  generateCustomReport,
  getCompanyReport,
  getGoals,
  createGoal,
  updateGoal,
  addGoalComment,
  getTrainingTypes,
  getEmployeeTrainingRecords,
  addTrainingRecord,
  getBenefitsOverview,
  listFiles,
  uploadFile,
  deleteFile,
  getJobListings,
  getApplications,
  getApplicationDetails,
  updateApplicationStatus,
  addApplicationComment,
  getAccountFields,
  getAccountMetadata
} from './tools';
import { employeeChanged } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    getEmployee,
    getEmployeeDirectory,
    createEmployee,
    updateEmployee,
    getTableData,
    upsertTableRow,
    deleteTableRow,
    getTimeOffRequests,
    createTimeOffRequest,
    updateTimeOffRequestStatus,
    getWhosOut,
    getTimeOffBalances,
    getTimeOffTypes,
    getTimesheetEntries,
    clockInOut,
    addTimesheetEntry,
    generateCustomReport,
    getCompanyReport,
    getGoals,
    createGoal,
    updateGoal,
    addGoalComment,
    getTrainingTypes,
    getEmployeeTrainingRecords,
    addTrainingRecord,
    getBenefitsOverview,
    listFiles,
    uploadFile,
    deleteFile,
    getJobListings,
    getApplications,
    getApplicationDetails,
    updateApplicationStatus,
    addApplicationComment,
    getAccountFields,
    getAccountMetadata
  ],
  triggers: [
    employeeChanged
  ]
});
