import { Slate } from 'slates';
import { spec } from './spec';
import {
  listChecks,
  getCheck,
  createCheck,
  updateCheck,
  deleteCheck,
  getCheckResults,
  getSummary,
  listContacts,
  createContact,
  updateContact,
  deleteContact,
  listTeams,
  createTeam,
  updateTeam,
  deleteTeam,
  listMaintenance,
  createMaintenance,
  updateMaintenance,
  deleteMaintenance,
  listTmsChecks,
  getTmsCheck,
  deleteTmsCheck,
  performSingleCheck,
  getProbes,
  getAccountInfo,
  getActions,
  getAnalysis
} from './tools';
import { stateChange } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    listChecks,
    getCheck,
    createCheck,
    updateCheck,
    deleteCheck,
    getCheckResults,
    getSummary,
    listContacts,
    createContact,
    updateContact,
    deleteContact,
    listTeams,
    createTeam,
    updateTeam,
    deleteTeam,
    listMaintenance,
    createMaintenance,
    updateMaintenance,
    deleteMaintenance,
    listTmsChecks,
    getTmsCheck,
    deleteTmsCheck,
    performSingleCheck,
    getProbes,
    getAccountInfo,
    getActions,
    getAnalysis
  ],
  triggers: [stateChange]
});
