import {
  Slate } from 'slates';
import { spec } from './spec';
import {
  getActor,
  listWorkspaces,
  getWorkspace,
  createWorkspace,
  updateWorkspace,
  deleteWorkspace,
  executeQuery,
  listConnections,
  createConnection,
  updateConnection,
  deleteConnection,
  testConnection,
  listOrganizations,
  getOrganization,
  createOrganization,
  updateOrganization,
  deleteOrganization,
  listOrgMembers,
  manageOrgMember,
  listPipelines,
  runPipeline,
  listProcesses,
  getProcess,
  listSnapshots,
  getSnapshot,
} from './tools';
import {
  processActivity,
  inboundWebhook,
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    getActor,
    listWorkspaces,
    getWorkspace,
    createWorkspace,
    updateWorkspace,
    deleteWorkspace,
    executeQuery,
    listConnections,
    createConnection,
    updateConnection,
    deleteConnection,
    testConnection,
    listOrganizations,
    getOrganization,
    createOrganization,
    updateOrganization,
    deleteOrganization,
    listOrgMembers,
    manageOrgMember,
    listPipelines,
    runPipeline,
    listProcesses,
    getProcess,
    listSnapshots,
    getSnapshot,
  ],
  triggers: [
    inboundWebhook,
    processActivity,
  ],
});
