import { Slate } from 'slates';
import { spec } from './spec';
import {
  getAccount,
  listTimeEntries,
  createTimeEntry,
  updateTimeEntry,
  deleteTimeEntry,
  manageTimer,
  listProjects,
  createProject,
  updateProject,
  deleteProject,
  listClients,
  manageClient,
  listLabels,
  manageLabel,
  deleteLabel,
  listTeams,
  manageTeam,
  deleteTeam,
  listUsers,
  listForecasts,
  manageForecast,
  deleteForecast,
  getReport,
  manageDayLock,
} from './tools';
import {
  timeEntryEvents,
  projectEvents,
  forecastEvents,
  labelEvents,
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    getAccount,
    listTimeEntries,
    createTimeEntry,
    updateTimeEntry,
    deleteTimeEntry,
    manageTimer,
    listProjects,
    createProject,
    updateProject,
    deleteProject,
    listClients,
    manageClient,
    listLabels,
    manageLabel,
    deleteLabel,
    listTeams,
    manageTeam,
    deleteTeam,
    listUsers,
    listForecasts,
    manageForecast,
    deleteForecast,
    getReport,
    manageDayLock,
  ],
  triggers: [
    timeEntryEvents,
    projectEvents,
    forecastEvents,
    labelEvents,
  ],
});
