import { Slate } from 'slates';
import { spec } from './spec';
import {
  createStory,
  getStory,
  updateStory,
  deleteStory,
  searchStories,
  manageStoryComments,
  manageStoryTasks,
  createEpic,
  getEpic,
  updateEpic,
  deleteEpic,
  listEpics,
  createIteration,
  updateIteration,
  listIterations,
  createObjective,
  updateObjective,
  listObjectives,
  listWorkflows,
  listMembers,
  listTeams,
  listLabels,
  listCustomFields,
  manageLabels,
  createDocument,
  getDocument,
  updateDocument
} from './tools';
import { workspaceEvents } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    createStory,
    getStory,
    updateStory,
    deleteStory,
    searchStories,
    manageStoryComments,
    manageStoryTasks,
    createEpic,
    getEpic,
    updateEpic,
    deleteEpic,
    listEpics,
    createIteration,
    updateIteration,
    listIterations,
    createObjective,
    updateObjective,
    listObjectives,
    listWorkflows,
    listMembers,
    listTeams,
    listLabels,
    listCustomFields,
    manageLabels,
    createDocument,
    getDocument,
    updateDocument
  ],
  triggers: [workspaceEvents]
});
