import {
  Slate } from 'slates';
import { spec } from './spec';
import {
  manageLead,
  getLead,
  listLeads,
  deleteLead,
  convertLead,
  manageContact,
  getContact,
  listContacts,
  deleteContact,
  manageAccount,
  getAccount,
  listAccounts,
  deleteAccount,
  manageDeal,
  getDeal,
  listDeals,
  deleteDeal,
  manageTask,
  listTasks,
  deleteTask,
  manageAppointment,
  listAppointments,
  deleteAppointment,
  manageNote,
  deleteNote,
  manageSalesActivity,
  searchRecords,
  listFilters,
  listSelectors,
  getFields,
} from './tools';
import {
  contactChanges,
  leadChanges,
  dealChanges,
  accountChanges,
  inboundWebhook,
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    manageLead,
    getLead,
    listLeads,
    deleteLead,
    convertLead,
    manageContact,
    getContact,
    listContacts,
    deleteContact,
    manageAccount,
    getAccount,
    listAccounts,
    deleteAccount,
    manageDeal,
    getDeal,
    listDeals,
    deleteDeal,
    manageTask,
    listTasks,
    deleteTask,
    manageAppointment,
    listAppointments,
    deleteAppointment,
    manageNote,
    deleteNote,
    manageSalesActivity,
    searchRecords,
    listFilters,
    listSelectors,
    getFields,
  ],
  triggers: [
    inboundWebhook,
    contactChanges,
    leadChanges,
    dealChanges,
    accountChanges,
  ],
});
