import { Slate } from 'slates';
import { spec } from './spec';
import {
  createUser,
  listUsers,
  readUser,
  updateUser,
  deleteUser,
  createMember,
  listMembers,
  readMemberStatus,
  updateMember,
  deleteMember,
  aggregateMember,
  resumeMfaChallenge,
  listAccounts,
  readAccount,
  listAccountNumbers,
  listTransactions,
  readTransaction,
  searchInstitutions,
  readInstitution,
  listHoldings,
  listStatements,
  fetchStatements,
  verifyMember,
  identifyMember,
  listAccountOwners,
  checkBalance,
  extendHistory,
  enhanceTransactions,
  requestWidgetUrl,
  listInsights,
  listCategories
} from './tools';
import {
  aggregationEvents,
  connectionStatusEvents,
  memberEvents,
  accountEvents,
  transactionEvents,
  statementEvents,
  userEvents,
  holdingEvents
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    createUser,
    listUsers,
    readUser,
    updateUser,
    deleteUser,
    createMember,
    listMembers,
    readMemberStatus,
    updateMember,
    deleteMember,
    aggregateMember,
    resumeMfaChallenge,
    listAccounts,
    readAccount,
    listAccountNumbers,
    listTransactions,
    readTransaction,
    searchInstitutions,
    readInstitution,
    listHoldings,
    listStatements,
    fetchStatements,
    verifyMember,
    identifyMember,
    listAccountOwners,
    checkBalance,
    extendHistory,
    enhanceTransactions,
    requestWidgetUrl,
    listInsights,
    listCategories
  ],
  triggers: [
    aggregationEvents,
    connectionStatusEvents,
    memberEvents,
    accountEvents,
    transactionEvents,
    statementEvents,
    userEvents,
    holdingEvents
  ]
});
