import { Slate } from 'slates';
import { spec } from './spec';
import {
  createTicket,
  getTicket,
  updateTicket,
  listTickets,
  deleteTicket,
  addTicketComment,
  addTicketThread,
  manageContact,
  listContacts,
  deleteContact,
  manageAccount,
  listAccounts,
  deleteAccount,
  search,
  manageArticle,
  listArticles,
  deleteArticle,
  listAgents,
  manageTask,
  listTasks,
  deleteTask,
  manageTimeEntry,
  listDepartments,
} from './tools';
import {
  ticketEvents,
  contactEvents,
  accountEvents,
  agentEvents,
  taskEvents,
  articleEvents,
  activityEvents,
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    createTicket,
    getTicket,
    updateTicket,
    listTickets,
    deleteTicket,
    addTicketComment,
    addTicketThread,
    manageContact,
    listContacts,
    deleteContact,
    manageAccount,
    listAccounts,
    deleteAccount,
    search,
    manageArticle,
    listArticles,
    deleteArticle,
    listAgents,
    manageTask,
    listTasks,
    deleteTask,
    manageTimeEntry,
    listDepartments,
  ],
  triggers: [
    ticketEvents,
    contactEvents,
    accountEvents,
    agentEvents,
    taskEvents,
    articleEvents,
    activityEvents,
  ],
});
