import { Slate } from 'slates';
import { spec } from './spec';
import {
  listSequences,
  addRecipientsToSequence,
  cancelSequence,
  listSequenceRecipients,
  sendEmail,
  listMessages,
  getMessage,
  createDraftMessage,
  sendDraftMessage,
  listTemplates,
  getTemplate,
  updateTemplate,
  deleteTemplate,
  sendTemplate,
  listContacts,
  createContact,
  updateContact,
  deleteContact,
  listMeetingTypes,
  manageMeetingType,
  listMeetingInvites,
  listRules,
  getRule,
  createRule,
  updateRule,
  deleteRule,
  listUnsubscribes,
  addUnsubscribe,
  removeUnsubscribe,
  getReportData,
  getLiveFeed,
  getUserProfile,
  listTeams,
  manageTeam,
  listTeamMembers,
  manageTeamMembership,
  listPolls,
  getPoll,
  searchSalesforce,
  manageSalesforceRecord
} from './tools';
import {
  messageEvents,
  engagementEvents,
  pollEvents,
  meetingEvents,
  unsubscribeEvents
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    listSequences,
    addRecipientsToSequence,
    cancelSequence,
    listSequenceRecipients,
    sendEmail,
    listMessages,
    getMessage,
    createDraftMessage,
    sendDraftMessage,
    listTemplates,
    getTemplate,
    updateTemplate,
    deleteTemplate,
    sendTemplate,
    listContacts,
    createContact,
    updateContact,
    deleteContact,
    listMeetingTypes,
    manageMeetingType,
    listMeetingInvites,
    listRules,
    getRule,
    createRule,
    updateRule,
    deleteRule,
    listUnsubscribes,
    addUnsubscribe,
    removeUnsubscribe,
    getReportData,
    getLiveFeed,
    getUserProfile,
    listTeams,
    manageTeam,
    listTeamMembers,
    manageTeamMembership,
    listPolls,
    getPoll,
    searchSalesforce,
    manageSalesforceRecord
  ],
  triggers: [messageEvents, engagementEvents, pollEvents, meetingEvents, unsubscribeEvents]
});
