import { Slate } from 'slates';
import { spec } from './spec';
import {
  listSitesTool,
  getSiteTool,
  listUnitsTool,
  getUnitTool,
  listUsersTool,
  getUserTool,
  createUserTool,
  updateUserTool,
  listInvoicesTool,
  getInvoiceTool,
  createInvoiceTool,
  manageInvoiceTool,
  listUnitRentalsTool,
  manageMoveInTool,
  manageMoveOutTool,
  manageValetOrderTool,
  manageLeadTool,
  getSettingsTool,
} from './tools';
import {
  unitEventsTrigger,
  moveInEventsTrigger,
  moveOutEventsTrigger,
  invoiceEventsTrigger,
  userEventsTrigger,
  unitRentalEventsTrigger,
  valetOrderEventsTrigger,
  siteEventsTrigger,
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    listSitesTool,
    getSiteTool,
    listUnitsTool,
    getUnitTool,
    listUsersTool,
    getUserTool,
    createUserTool,
    updateUserTool,
    listInvoicesTool,
    getInvoiceTool,
    createInvoiceTool,
    manageInvoiceTool,
    listUnitRentalsTool,
    manageMoveInTool,
    manageMoveOutTool,
    manageValetOrderTool,
    manageLeadTool,
    getSettingsTool,
  ],
  triggers: [
    unitEventsTrigger,
    moveInEventsTrigger,
    moveOutEventsTrigger,
    invoiceEventsTrigger,
    userEventsTrigger,
    unitRentalEventsTrigger,
    valetOrderEventsTrigger,
    siteEventsTrigger,
  ],
});
