import { Slate } from 'slates';
import { spec } from './spec';
import {
  createInvoice,
  getInvoice,
  listInvoices,
  updateInvoice,
  createContact,
  getContact,
  listContacts,
  updateContact,
  listContactGroups,
  getContactGroup,
  createContactGroup,
  updateContactGroup,
  addContactsToContactGroup,
  removeContactFromContactGroup,
  createPayment,
  listPayments,
  deletePayment,
  createCreditNote,
  listCreditNotes,
  updateCreditNote,
  createBankTransaction,
  listBankTransactions,
  listBankTransfers,
  getBankTransfer,
  createBankTransfer,
  listAccounts,
  createAccount,
  updateAccount,
  createPurchaseOrder,
  listPurchaseOrders,
  updatePurchaseOrder,
  createQuote,
  listQuotes,
  updateQuote,
  listItems,
  createItem,
  updateItem,
  createManualJournal,
  listManualJournals,
  getReport,
  getOrganisation,
  getSettings
} from './tools';
import { invoiceChanges, contactChanges, paymentChanges, inboundWebhook } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    createInvoice,
    getInvoice,
    listInvoices,
    updateInvoice,
    createContact,
    getContact,
    listContacts,
    updateContact,
    listContactGroups,
    getContactGroup,
    createContactGroup,
    updateContactGroup,
    addContactsToContactGroup,
    removeContactFromContactGroup,
    createPayment,
    listPayments,
    deletePayment,
    createCreditNote,
    listCreditNotes,
    updateCreditNote,
    createBankTransaction,
    listBankTransactions,
    listBankTransfers,
    getBankTransfer,
    createBankTransfer,
    listAccounts,
    createAccount,
    updateAccount,
    createPurchaseOrder,
    listPurchaseOrders,
    updatePurchaseOrder,
    createQuote,
    listQuotes,
    updateQuote,
    listItems,
    createItem,
    updateItem,
    createManualJournal,
    listManualJournals,
    getReport,
    getOrganisation,
    getSettings
  ],
  triggers: [inboundWebhook, invoiceChanges, contactChanges, paymentChanges]
});
