import {
  Slate } from 'slates';
import { spec } from './spec';
import {
  createJob,
  getJob,
  updateJob,
  searchJobs,
  duplicateJob,
  addJobComment,
  manageJobPlan,
  createCompany,
  getCompany,
  updateCompany,
  createContact,
  getContact,
  updateContact,
  logTime,
  getTimeEntry,
  updateTimeEntry,
  deleteTimeEntry,
  createExpense,
  getExpense,
  updateExpense,
  getInvoice,
  updateInvoice,
  recordInvoicePayment,
  searchInvoices,
  getQuote,
  manageLabels,
  listUsers,
  listRoles,
  getOrganisation,
} from './tools';
import {
  newJob,
  newInvoice,
  newCompany,
  inboundWebhook,
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    createJob,
    getJob,
    updateJob,
    searchJobs,
    duplicateJob,
    addJobComment,
    manageJobPlan,
    createCompany,
    getCompany,
    updateCompany,
    createContact,
    getContact,
    updateContact,
    logTime,
    getTimeEntry,
    updateTimeEntry,
    deleteTimeEntry,
    createExpense,
    getExpense,
    updateExpense,
    getInvoice,
    updateInvoice,
    recordInvoicePayment,
    searchInvoices,
    getQuote,
    manageLabels,
    listUsers,
    listRoles,
    getOrganisation,
  ],
  triggers: [
    inboundWebhook,
    newJob,
    newInvoice,
    newCompany,
  ],
});
