import { Slate } from 'slates';
import { spec } from './spec';
import {
  generateText,
  createResponse,
  getResponse,
  deleteResponse,
  listResponseInputItems,
  generateImage,
  createEmbeddings,
  moderateContent,
  listModels,
  createFineTuningJob,
  getFineTuningJob,
  cancelFineTuningJob,
  uploadFile,
  listFiles,
  getFile,
  getFileContent,
  deleteFile,
  createVectorStore,
  listVectorStores,
  getVectorStore,
  updateVectorStore,
  searchVectorStore,
  deleteVectorStore,
  addVectorStoreFile,
  listVectorStoreFiles,
  getVectorStoreFile,
  getVectorStoreFileContent,
  removeVectorStoreFile,
  createBatch,
  getBatch,
  cancelBatch,
  synthesizeSpeech,
  transcribeAudio,
  translateAudio
} from './tools';
import { openaiEvents } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    generateText,
    createResponse,
    getResponse,
    deleteResponse,
    listResponseInputItems,
    generateImage,
    createEmbeddings,
    moderateContent,
    listModels,
    createFineTuningJob,
    getFineTuningJob,
    cancelFineTuningJob,
    uploadFile,
    listFiles,
    getFile,
    getFileContent,
    deleteFile,
    createVectorStore,
    listVectorStores,
    getVectorStore,
    updateVectorStore,
    searchVectorStore,
    deleteVectorStore,
    addVectorStoreFile,
    listVectorStoreFiles,
    getVectorStoreFile,
    getVectorStoreFileContent,
    removeVectorStoreFile,
    createBatch,
    getBatch,
    cancelBatch,
    synthesizeSpeech,
    transcribeAudio,
    translateAudio
  ],
  triggers: [openaiEvents]
});
